In [70]:
import numpy as np

In [23]:
a = np.array([1,2,3,45])
a - np.mean(a, axis=0)

array([-11.75, -10.75,  -9.75,  32.25])

In [104]:
b = [[1,2,4,5], [1,4,6,7]]


In [4]:
b = np.random.randint(4,size=(4,4))
a = np.array([0,1,2,3])
a, b

(array([0, 1, 2, 3]), array([[1, 0, 0, 2],
        [3, 1, 0, 1],
        [2, 2, 2, 3],
        [2, 0, 3, 2]]))

In [81]:
c = b[np.arange(4),a]
print(b.shape)
print(a.shape)

(4, 4)
(4,)


In [82]:
margin = b - c + 1

In [102]:
aux = np.maximum(0, margin)
loss = np.sum(aux, axis=1)
aux, loss

(array([[1, 1, 3, 4],
        [0, 1, 2, 1],
        [0, 1, 1, 2],
        [0, 0, 4, 1]]), array([9, 4, 4, 5]))

In [87]:
final = loss - margin[np.arange(4),a]
np.sum(final)

18

In [80]:
c == b[np.arange(4),a]

array([ True,  True,  True,  True])

In [3]:
b

NameError: name 'b' is not defined

In [45]:
a = [1,2,3,4]

In [49]:
np.arange(a)

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [57]:
a = [[1,9,5,0,8],[1,5,4,6,9]]
np.argmax(a, axis=0)

array([0, 0, 0, 1, 1])

In [58]:
a = {}

In [61]:
a['hola', 'perro'] = 1+3

In [77]:
a = np.array([[1,4],[5,6]])
np.amax(a, axis=1)

array([4, 6])

In [82]:
a -= np.amax(a, axis=1)

In [81]:
a[]

array([-5,  1])

In [35]:
import numpy as np
b = np.random.randint(4,size=(4,4))
b

array([[3, 1, 2, 1],
       [0, 2, 3, 3],
       [3, 1, 0, 3],
       [3, 0, 1, 3]])

In [30]:
b[-1,:]

array([0, 3, 3, 0])

In [31]:
np.delete(b, -1, axis=0)

array([[3, 0, 3, 2],
       [1, 1, 2, 0],
       [1, 3, 1, 1]])

In [36]:
b[b <= 1] = 0

In [37]:
b[ b > 1] = 1

In [48]:
b

array([[1, 0, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1]])

In [47]:
a = np.random.randint(10, size=(4,4))
a

array([[8, 3, 5, 8],
       [4, 4, 1, 0],
       [9, 5, 2, 0],
       [6, 8, 1, 8]])

In [51]:
(b!=0)

array([[ True, False,  True, False],
       [False,  True,  True,  True],
       [ True, False, False,  True],
       [ True, False, False,  True]])

In [50]:
a*b

array([[8, 0, 5, 0],
       [0, 4, 1, 0],
       [9, 0, 0, 0],
       [6, 0, 0, 8]])